gyro mask quality of life and scripts/kst updates/fixes
tim-balloon/TIMflight pull request #132
Opened 2024-09-07 20:16 UTC by evanmayer

* Feature: dedicated command to allow/veto all channels of gyro1/gyro2 at once to cleanly swap between gyros
* etc & scripts cleanup from testing and launch attempt; getting star cam stuff under version control
* kst changes

2024-09-10 15:01 UTC, ianlowe13 requested changes

2024-09-10 17:20 UTC, shubhagrawal30 commented
looks good to me, other than Ian's comment

2024-09-11 00:00 UTC, evanmayer commented on mcp/motors/motors.c
Which comment? The file header?

2024-09-11 00:05 UTC, evanmayer commented
Updated comment to reflect significant controller changes

2024-09-11 03:23 UTC, ianlowe13 approved these changes

2024-09-11 21:21 UTC, merged