[Groundhog] An EVTM listener implementation + basic testing framework
tim-balloon/TIMflight pull request #65
Opened 2023-09-27 08:04 UTC by shubhagrawal30

Groundhog and BITServer code for receiving UDP multicast through the LOS/biphase and TDRSS/highrate EVTM downlinks. Also, starting a testing framework for groundhog.

Sender in MCP was implemented in #63.  

### Scope:

- _content_ changes made for new groundhog `evtm` code
- no _content_ changes made to the old groundhog code. Overall, several formatting changes to pass the _style checker/linter_
- adding `CMakeList` stuff for testing
- exhaustive (?) test code for the new `evtm` code
- no test code (yet) for the other downlinks
- no changes for possible integration with code for Iridium Pilot

### TODOs for new GSs or FCs for testing:

1. _Turn off `ufw` firewall on the ground station: **run `sudo ufw allow 20001/udp` and `sudo ufw allow 20001/udp` to get incoming UDP traffice on the relevent ports!**
2. On your flight computer, add a default gateway to the gondola network config in `/etc/netplan/00-installer-config.yaml`: 
&nbsp;  &nbsp;  `routes:`
&nbsp;  &nbsp;  &nbsp;  &nbsp;  `- to: default`
&nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  `via: 192.168.1.1`

2023-09-28 19:08 UTC, ianlowe13 reviewed
see comments

2023-09-28 19:08 UTC, ianlowe13 commented on groundhog/blast/main.c
>    int pilot_on = 1;
deprecated comment

2023-09-28 19:08 UTC, ianlowe13 commented on groundhog/blast/main.c
>      if (strcmp(argv[i], "-no_pilot") == 0) pilot_on = 0;
more comments about deprecated modes to be removed

2023-09-28 22:58 UTC, shubhagrawal30 commented on common/bitserver.c
> +    blast_info("-> Multicast mode: %s:%d", recv_addr, port);
not really, changed it.

2023-09-28 23:04 UTC, shubhagrawal30 commented on groundhog/blast/highrate.c
> +/**
yeah, I do not know who wrote this/copyright. This is needed to pass the linter though (groundhog was not style-checked before as it did not have a testing framework)

2023-09-28 23:04 UTC, shubhagrawal30 commented on groundhog/blast/highrate.c
> -
I don't know how this passed the linter, haha

2023-09-29 02:25 UTC, shubhagrawal30 commented
Also adding in EVTM commanding code! tangentially related to this PR overall, but still a good addition to review here.

2023-09-29 18:47 UTC, ianlowe13 requested changes
Shubh, do you know if the pilot link has any "in charge" protections? Maybe in bitsender? I think all links should only send telemetry if InCharge == 1 but it would be nice to double check.

2023-09-29 18:47 UTC, ianlowe13 commented on groundhog/blast/highrate.c
>            gse_packet_header.size = 2048;
magic numbers should be #define

2023-09-29 20:10 UTC, shubhagrawal30 commented
> Shubh, do you know if the pilot link has any "in charge" protections? Maybe in bitsender? I think all links should only send telemetry if InCharge == 1 but it would be nice to double check.

Yup. In either one's infinite loop, stuff is only compressed and sent to BITSender when the thread is running on the InCharge computer.

`if (!fifoIsEmpty(es->evtm_fifo) && es->ll && InCharge) { // data ready to send` in `evtm.c:164`

`if (!fifoIsEmpty(&pilot_fifo) && ll && InCharge) { // data is ready to be sent` in `pilot.c:116`

2023-10-01 21:11 UTC, evanmayer requested changes

2023-10-05 18:15 UTC, shubhagrawal30 commented on common/bitserver.c
> +  if (dot != NULL) {
The best/easiest thing to do is to just check if the dot address is within 4 of the recv_addr, I have added that.

2023-10-05 18:20 UTC, evanmayer commented
For future reference, reviewers should resolve their comments when they're satisfied with your changes (after a commit), or once they agree with your pushback on changes that you argue aren't necessary. This helps make sure that reviewers know their comments have been addressed. But it does require reviewers to be attentive.

2023-10-05 18:28 UTC, shubhagrawal30 commented on groundhog/blast/tests/test_gh_evtm.c
> +    for (int evtm_type = LOS_EVTM; evtm_type <= TDRSS_EVTM; evtm_type++) {
would this concern be gone with the use of a few strategically placed printf's?

2023-10-05 18:36 UTC, shubhagrawal30 commented on groundhog/blast/tests/test_gh_evtm.c
> +    for (int evtm_type = LOS_EVTM; evtm_type <= TDRSS_EVTM; evtm_type++) {
Nvm, I can do this another way

2023-10-05 18:39 UTC, evanmayer commented on groundhog/blast/tests/test_gh_evtm.c
> +    for (int evtm_type = LOS_EVTM; evtm_type <= TDRSS_EVTM; evtm_type++) {
Can you functionalize this loop body and break each test case out into a separate call to `cmocka_unit_test`? printfs may help track down what failed, or they may get lost in the noise, but the problem here is that if you lump all your tests together (hyperbole) under one `cmocka_unit_test` call, the unit test will report as failed and stop executing if **any** assertion is failed, so you won't have a good idea about which things failed and which things didn't. With separate test invocations for each separate case being tested, even the non-failing tests scheduled after the failing test will still be executed.

2023-10-05 18:42 UTC, shubhagrawal30 commented
Ah sure, we could do that. I meant to _resolve_ them as a way to track that I have addressed them. But the other way also sounds fine.

2023-10-05 18:43 UTC, shubhagrawal30 commented
> Can you functionalize this loop body and break each test case out into a separate call to `cmocka_unit_test`? printfs may help track down what failed, or they may get lost in the noise, but the problem here is that if you lump all your tests together (hyperbole) under one `cmocka_unit_test` call, the unit test will report as failed and stop executing if **any** assertion is failed, so you won't have a good idea about which things failed and which things didn't. With separate test invocations for each separate case being tested, even the non-failing tests scheduled after the failing test will still be executed. 

yup, that is what I have done now.

2023-10-16 18:02 UTC, ianlowe13 submitted a review, later dismissed

2023-10-16 18:02 UTC, ianlowe13 commented on mcp/commanding/commands.c
> +        case enable_evtm:
same for disable

2023-11-14 20:07 UTC, shubhagrawal30 commented on groundhog/blast/evtm.c
> +                                                                                             NULL, NULL, NULL, GROUNDHOG_EXTRACT_TO_DISK);
close to function opening "("? at least that is the rough convention I have been going off from. If we don't like that, let me know.

2023-11-14 20:45 UTC, shubhagrawal30 commented on groundhog/blast/tests/test_gh_evtm.c
> +static int GH_EVTM_teardown_tests(void **state) {
I was infact leaking memory there. I could not figure out how to fix it directly though (`free`-ing `state+2` and `state+3` was weirdly seg-faulting). So I did the normal perfectly reasonable thing and rewrote that portion of code.

2023-11-14 22:07 UTC, shubhagrawal30 commented on mcp/commanding/commands.c
> +        case enable_evtm:
done

2023-11-14 22:16 UTC, ianlowe13 reviewed
My issues have been addressed in new changes

2023-11-15 21:49 UTC, evanmayer approved these changes

2023-11-15 22:08 UTC, ianlowe13 approved these changes

2023-11-16 00:22 UTC, merged

2024-03-12 23:15 UTC, evanmayer commented
Update: looks like the flight computer had a problem with the edits to the above netplan file, and we had to remove the file from `/etc/netplan` dir to get the star camera computer, which we were using as a ground station, to connect to anything. We tested reception of telemetry in this situation and it seems that the above changes are not necessary...