Iandev main
tim-balloon/TIMflight pull request #72
Opened 2023-11-03 17:20 UTC by ianlowe13

Addresses issue #69 in adding the error code telemetry channels as well as the state channels to MCP.

2023-11-03 17:21 UTC, ianlowe13 commented
This code is big and ugly, but in the name of making it more readable I have tried not to "save E ink" and give everything their own lines.

2023-11-05 22:03 UTC, evanmayer requested changes

2023-11-05 22:15 UTC, evanmayer requested changes

2023-11-05 22:15 UTC, evanmayer commented on mcp/motors/motors.c
> + * @brief setups up channel pointers to reaction wheel error
Couple of typos in this docstring

2023-11-06 16:54 UTC, evanmayer requested changes

2023-11-06 16:54 UTC, evanmayer commented on mcp/motors/motors.c
> +        piv_mc_state_Addr = channels_find_by_name("state_piv_mc");
Still needs `first_time = 0;`

2023-11-06 17:17 UTC, evanmayer approved these changes

2023-11-06 17:17 UTC, merged