Star camera triggering
tim-balloon/TIMflight pull request #74
Opened 2024-01-30 21:40 UTC by ianlowe13

I have added logic to trigger the star cameras off of the gyro data, based on a 1 pixel streaking limit. I have also added functions that allow us to command these variables.

2024-01-30 23:26 UTC, evanmayer commented
I don't see anything in here about gyros or streaking. Is that somewhere else, like a previous commit that's already merged?

2024-01-31 16:25 UTC, ianlowe13 commented
> I don't see anything in here about gyros or streaking. Is that somewhere else, like a previous commit that's already merged?

Sorry, I forgot I merged those changes last year after I got all of them working. Work was mostly on the SC repo this time around and minimal MCP stuff to conform with the required changes on that side.

2024-01-31 17:57 UTC, evanmayer approved these changes

2024-01-31 19:32 UTC, evanmayer requested changes

2024-01-31 19:32 UTC, evanmayer commented on mcp/sensors/star_camera_trigger.c
> +                    // testing latency
Removed (or comment, if you must) unused function call.

2024-01-31 22:35 UTC, evanmayer approved these changes

2024-01-31 22:40 UTC, merged