Overhaul inclinometer code
tim-balloon/TIMflight pull request #88
Opened 2024-05-29 02:32 UTC by evanmayer

### Summary

Bugfix inclinometer code that would often throw checksum errors, sometimes segfault on init, and report incorrect angle values for certain angles.

### Background

Each flight computer has its own independent inclinometer. The devices will have the same internal serial number, so the same code runs on each FC.

### Details

Overall control flow of initializing, reading from serial, checking for errors, and reconnecting stays the same. Guts of the algorithm refactored for readability, testability, and correctness. The core algorithm that unpacks data from each message is lifted from the Jewell manual for this device, so it is "known" to be correct. Trust, but verify: in addition, `cmocka` test code was added for the new core functions, and the tests take canned real inclinometer data as input to check against the functions.

Additional improvements:

* Independent TM channels, veto, commanding, and contributions to pointing solutions for each inclinometer
* `udev` rules updates to make connecting to serial/usb devices more robust/generic
* Reorganization of shell scripts to make repetitive build/upload/start/stop tasks easier

I added some comments here on the Pull Request to help you find your way around this substantial review.

### Follow-on:

Explore possibility of updating ElSolutionStruct variance to give inclinometers more sway over elevation solution. These are better than what BLAST-TNG flew, and the the bugs ironed out, should be reliable, although somewhat low resolution.

2024-05-29 02:34 UTC, evanmayer commented on blast_config/command_list.c
Veto/allow incs separately

2024-05-29 02:35 UTC, evanmayer commented on blast_etc/chrony/chrony.conf
Getting Adrian's chrony time server conf file under version control

2024-05-29 02:35 UTC, evanmayer commented on blast_etc/systemd/flight_software.service
This config file handles launching blastcmd and the infinite mcp restart loop upon boot.

2024-05-29 02:36 UTC, evanmayer commented on install_and_restart_mcp.sh
Split into two scripts

2024-05-29 02:38 UTC, evanmayer commented on mcp/include/motors.h
Temporarily hamstring el axis until hard stops are in place. Little danger of this making it into flight, since this won't be enough to move the mass model, and we'll find out that way.

2024-05-29 02:39 UTC, evanmayer commented on mcp/mcp.c
Restore incs to operation

2024-05-29 02:39 UTC, evanmayer commented on mcp/mcp_inf_loop
Was vestigial/conflicting with the more up to date `blast_inf_loop` we pirated from the old BLAST-TNG FCs.

2024-05-29 02:40 UTC, evanmayer commented on mcp/pointing/pointing.c
Incorporate both inclinometers into pointing solution

2024-05-29 02:44 UTC, evanmayer commented on scripts/inflight/start_gps_time_software.sh
Mostly lifted from one of Adrian's scripts

2024-05-29 02:45 UTC, evanmayer commented on scripts/uploading/upload_scripts.sh
Critical for uploading non-flight-code config files that are required for the FCs to function. Mostly for connecting to devices in repeatable ways the flight software expects

2024-05-29 22:06 UTC, ianlowe13 requested changes

2024-06-03 16:14 UTC, evanmayer commented on legacyMCP/housekeeping/outer_frame.c
Check now!

2024-06-03 19:01 UTC, ianlowe13 approved these changes

2024-06-03 19:06 UTC, merged